# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#title: Your awesome title
#email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://example.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
# theme: minima

exclude:
  - README.md
  - CONTRIBUTING.md
  - Dockerfile
  - Dockerfile.base
  - Gemfile
  - Gemfile.lock
  - bower.json
  - bower_components/patternfly/tests
  - bower_components/bootstrap-datepicker
  - bower_components/eonasdan-bootstrap-datetimepicker
  - openshift/README.md

collections:
  faqs:
    output: true # this is to workaround issue #161 in jekyll-asciidoc
    permalink: /collections/:collection/:path # this is also part of the workaround
  howdoi:
    output: true # this is to workaround issue #161 in jekyll-asciidoc
    permalink: /collections/:collection/:path # this is also part of the workaround
  presentations:
    output: true # this is to workaround issue #161 in jekyll-asciidoc
    permalink: /collections/:collection/:path # this is also part of the workaround
  projects:
    output: true # this is to workaround issue #161 in jekyll-asciidoc
    permalink: /collections/:collection/:path # this is also part of the workaround
  applications:
    output: true
  examples:
    output: true

defaults:
- scope:
    path: ""
  values:
    menu_template: menu_radanalytics.html
    menu_entry: Welcome

asciidoc:
  ext: adoc
asciidoctor: {}
